version: '3'
services:

  mysql:
    image: mysql/mysql-server:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: webhook
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_HOST: '%'
    ports:
    - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
    - 9090:8080

  webhook-service:
    image: joanluk/webhook-service:latest
    ports:
    - 8080:8080
    depends_on:
    - mysql

